### ISSUE TITLE
Image Asset Field always comes back with null values

### ISSUE THREAD

**Issue by ChadAlanJackson** [kffein/Craft-export-Csv#8] opened 2019-03-14 19:01 UTC
Even with an image asset selected for example this should return `Smart-Speak.jpg` (along with all of the rest of the asset data, instead, the export is returning this:

`{"volumeId":null,"folderId":null,"filename":null,"kind":null,"width":null,"height":null,"size":null,"dateModified":null,"includeSubfolders":false,"withTransforms":null,"elementType":"craft\\elements\\Asset","query":null,"subQuery":null,"contentTable":"{{%content}}","customFields":null,"inReverse":false,"asArray":false,"id":null,"uid":null,"fixedOrder":false,"status":["enabled"],"archived":false,"trashed":false,"dateCreated":null,"dateUpdated":null,"siteId":1,"enabledForSite":true,"leaves":false,"relatedTo":null,"title":null,"slug":null,"uri":null,"search":null,"ref":null,"with":null,"orderBy":{"relations.sortOrder":4},"withStructure":null,"structureId":null,"level":null,"hasDescendants":null,"ancestorOf":null,"ancestorDist":null,"descendantOf":null,"descendantDist":null,"siblingOf":null,"prevSiblingOf":null,"nextSiblingOf":null,"positionedBefore":null,"positionedAfter":null,"select":["**"],"selectOption":null,"distinct":null,"from":null,"groupBy":null,"join":[["INNER JOIN","{{%relations}} relations",["and","[[relations.targetId]] = [[elements.id]]",{"relations.sourceId":"9980","relations.fieldId":"104"},["or",{"relations.sourceSiteId":null},{"relations.sourceSiteId":"1"}]]]],"having":null,"union":null,"params":[],"queryCacheDuration":null,"queryCacheDependency":null,"where":null,"limit":"1","offset":null,"indexBy":null,"emulateExecution":false}`

**Comment by jlachancekffein** [comment] 2019-04-24 13:51
Duplicate of #4

**Comment by jlachancekffein** [comment] 2019-04-24 15:06
Please update to v1.0.7 version of the plugin. We now returning the url of the first asset related to the export.

**Closed as completed by jlachancekffein** 2019-04-24 15:06 UTC
Labels: duplicate
